"""clients table + appointments.client_id

Revision ID: 89b29a9a65a1
Revises: 2b8b9190513e
Create Date: 2026-07-27 17:42:11.038479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b29a9a65a1'
down_revision: Union[str, None] = '2b8b9190513e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('ix_clients_phone', ['phone'], unique=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_client_id'), ['client_id'], unique=False)
        # SQLite batch mode needs an explicit constraint name so the
        # ALTER TABLE emulation (rebuild + rename) can find it again on
        # downgrade. Anonymous constraints don't survive the rebuild.
        batch_op.create_foreign_key(
            'fk_appointments_client_id_clients',
            'clients', ['client_id'], ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_client_id_clients', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointments_client_id'))
        batch_op.drop_column('client_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_phone')

    op.drop_table('clients')
    # ### end Alembic commands ###
